### ISSUE TITLE
OpenWeatherMap API Key

### ISSUE THREAD

**Issue by jslnriot** [bjdixon/weather-app#1]
OpenWeatherMap recently implemented the need to use an API key.
http://openweathermap.org/appid

In your formatWeather() function you can add it to the request link once you register for an account.

**Comment by bjdixon** [comment]
Thanks @jslnriot.

If you want to submit a PR you can use this API key: `6cba3a4c3d666fe9b486db2c5d8329db`

**Comment by bjdixon** [comment]
Closed by #2
